### ISSUE TITLE
Support multiple user environments

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/editor#10]
The RPC team currently runs MacOS on MacBook Pros (with either Intel 64 or M1 chips). At a minimum, the editor should run in this environment. However, there will be other users of this software, and it should be Windows and Linux compatible.

**Comment by NGPixel** [comment]
The editor is already being built for the following targets:

- Linux x64
- Linux arm64
- macOS x64
- macOS arm64 (aka Apple Silicon)
- Windows x64
- Windows arm64

(e.g. https://github.com/ietf-tools/editor/releases/tag/0.3.1)
