### ISSUE TITLE
Ability to check for correct use of indefinite articles (a/an)

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/editor#14]
This functionality is currently captured in the ckarticles script, which prints to stdout suspect use:
```
*** Part 1: a -> an ('a attribute') ***
*** Part 2: an -> a ('an protocol') ***
*** Part 3: an -> a (tricky ones from the articles list) ***
```
The articles list as coded in ckarticles is the following: AAA, FEC, FIR, LF, LIS, LRDD, MEG, MEP, MRHOF, MIC, NAPTR, NAT, NAS, RAS, ROHC, RPL, RST, SAFI, SCSI, SID, SIP, SMPTE, SYN, rinit

For example, "AAA" is pronounced "triple-A", so its indefinite article should be "a" and not "an". 

The checker should let the user step through each suspect instance and allow them to correct it or skip to the next suspect article.

**Comment by NGPixel** [comment]
Added in 0.24.0
