### ISSUE TITLE
Ability to check for non-inclusive language

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/editor#20]
The user should be able to create a simple text report that shows where non-inclusive language is used. For example:
```
Check for "native".
775:      distributed through the native methods in the TSCH MAC layer and
1980:   There are two modes for a Track: an IPv6 native mode and a protocol-
1983:4.6.1.1.  Native Mode
1985:   In native mode, the Protocol Data Unit (PDU) is associated with flow-
2023:                  Figure 11: Track Forwarding, Native Mode
```
The RPC does not make edits in these cases; they only ask authors to review the guidance at https://www.rfc-editor.org/styleguide/part2/#inclusive_language and list the words that were flagged (if any). 

It is sufficient to display the report in a dialog box. The report does not need to be saved out. 

This functionality is currently provided by the inclusive script.

**Comment by NGPixel** [comment]
Added in 0.22.2
