### ISSUE TITLE
Install package broken on Apple Sillicon

### ISSUE THREAD

**Issue by NGPixel** [ietf-tools/editor#29]
The macOS arm64 package distribution is broken because Apple requires native Apple sillicon apps to be notarized with an Apple developer certificate.

**Comment by richsalz** [comment]
So maybe don't post it in the downloads page?  It confused me for some time....

**Comment by NGPixel** [comment]
@richsalz We are working on getting an Apple dev certificate but it's quite a process. I've removed the mac arm64 target in the meantime.

**Comment by NGPixel** [comment]
Builds are now signed and notarized for arm64 and x64 targets.
