### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/editor#41]
After installing DraftForge 0.35.0, I received the following message when I started it again.

> Update Check Failed
> Error: Error: ZIP file not provided: [
> {
> "url": "https://github.com/ietf-tools/editor/releases/latest/download/ietf-draftforge-mac-x64-0.35.1.dmg",
> "info": {
> "url": "ietf-draftforge-mac-x64-0.35.1.dmg",
> "sha512": "3JwmWZuL/kBS70Z4dkdDrPaKPat6fzEXYP9haGnPkndyA9sS0Lm1KEfeGA/xXWdoUk7lLKQ8xQJzufrgNEMHjw==",
"size": 163391105
> }
> }
> ]

I was able to click Okay and go on.

**Comment by NGPixel** [comment]
Fixed in 0.35.2. You should be able to upgrade from the 0.35.0 build, just restart the app and the auto-updater should now work correctly.
