### ISSUE TITLE
repo directory is not created

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/editor#42]
When I clone a repo, I expect a directory named after the repo to be created for it. However, the files are placed in whichever directory is specified by Local Target Directory, currently set at /Users/jean/Documents/GitHub/.

For example, when I clone https://github.com/rfc-editor/rfc9245-AUTH48.git, the files are placed in /Users/jean/Documents/GitHub/ and not /Users/jean/Documents/GitHub/rfc9245-AUTH48. 

The description for Local Target Directory says, "The destination folder will be created automatically if it doesn't exist."  Should it instead say "Please specify a destination directory"? Or should DraftForge be creating a subdirectory underneath the Local Target Directory?

**Comment by NGPixel** [comment]
Added a new option "Clone in Subdirectory" in 0.35.4 which is on by default and replicates Git behavior:

![image](https://github.com/user-attachments/assets/1855fc8c-34d0-4387-8690-b0d102b5ea29)
